export const content = {
  es: {
    lang: 'es', locale: 'es_ES', path: '/', other: '/en', otherLabel: 'English',
    title: 'Datolens — Muchos datos. Todo más claro.',
    description: 'Abre CSV grandes, Excel, Parquet y SPSS en tu Mac. Explora variables, cruza filtros y crea gráficos para entender tus datos. Descarga la beta de Datolens.',
    skip: 'Saltar al contenido', explore: 'El producto', people: 'Para quién', questions: 'Preguntas', download: 'Descargar para Mac',
    eyebrow: 'LA CURIOSIDAD, EN SU ELEMENTO',
    hero: 'Muchos datos.<br>Todo más <em>claro.</em>',
    intro: 'Ese fichero enorme tiene algo que contarte. <br>Ábrelo, explóralo y encuentra la historia, en tu Mac.',
    watch: 'Ver el producto', release: 'BETA 0.1 · MACOS · APPLE SILICON',
    demoLabel: 'Capturas reales de Datolens · datos de ejemplo', demoFile: 'vivienda_demo.csv',
    demoHint: 'Tabla, exploración y gráficos.', all: 'Todas', cities: ['Madrid', 'Barcelona', 'Valencia', 'Sevilla'],
    rows: 'filas', vars: 'variables', table: 'Tabla', distribution: 'Explorar', chart: 'Gráfico',
    stepTitles: ['Abre el fichero.', 'Sigue una pista.', 'Hazlo visible.'],
    stepSubtitles: ['Empieza por lo que tienes.', 'Cruza filtros. Conecta variables.', 'De la pregunta al gráfico.'],
    demoXAxis: 'Superficie · m²', demoYAxis: 'Precio · €', demoBarTitle: 'Precio medio por ciudad',
    demoFields: ['Ciudad', 'Superficie', 'Precio', 'Habitaciones'],
    demoVariables: 'Tus variables, a la vista', demoNote: 'Filtra por ciudad y observa cómo cambian los datos.',
    play: 'Reanudar animación', pause: 'Pausar animación',
    formatKicker: 'TUS FICHEROS DE SIEMPRE. OTRA FORMA DE MIRARLOS.',
    statementKicker: 'MENOS PREPARATIVOS. MÁS DESCUBRIMIENTOS.',
    statement: 'Has venido a entender los datos.<br><span>Empieza por ahí.</span>',
    features: [
      { n: '01', title: 'El conjunto.<br>Y cada detalle.', text: 'Cientos de variables no tienen por qué ser cientos de incógnitas. Recorre sus distribuciones, encuentra valores vacíos y localiza lo que se sale de lo habitual.', tag: 'DISTRIBUCIONES · ESTADÍSTICAS · TIPOS' },
      { n: '02', title: 'Una pregunta.<br>La siguiente pista.', text: 'Selecciona un rango, filtra una categoría y mira qué cambia en el resto. Explora relaciones sin perder el hilo entre hojas y archivos.', tag: 'FILTROS CONECTADOS · VARIOS ARCHIVOS' },
      { n: '03', title: 'Del «creo que»<br>al «mira esto».', text: 'Barras, dispersión, series temporales y tablas dinámicas. Elige tus variables, encuentra una perspectiva y exporta el gráfico para tu próximo informe.', tag: 'GRÁFICOS · EXPORTACIÓN PNG, SVG Y CSV' },
    ],
    scaleKicker: 'PARA FICHEROS CON MUCHO QUE DECIR',
    scaleTitle: 'Grande el fichero.<br><em>Ligero el trabajo.</em>',
    scaleText: 'Millones de filas. Miles de variables. Datolens trabaja con un motor de datos local y muestra lo que necesitas explorar. Puedes usar una muestra para orientarte y el conjunto completo para profundizar.',
    scaleNote: 'El tiempo de apertura depende del formato, el tamaño y tu Mac. CSV y Excel necesitan una importación inicial.',
    scaleLegend: ['Una fila. Una posibilidad.', 'Explora una muestra o el conjunto completo.'],
    peopleKicker: 'PARA QUIENES SIEMPRE TIENEN OTRA PREGUNTA',
    peopleTitle: 'El próximo hallazgo<br>puede ser <em>el tuyo.</em>',
    peopleItems: [
      ['Análisis de datos', 'Ese extracto que acaba de llegar.', 'Inspecciona un archivo, comprueba distribuciones y encuentra las variables que merecen tu atención.'],
      ['Periodismo de datos', 'La historia entre miles de filas.', 'Explora datos públicos, compara grupos y lleva un gráfico a la próxima reunión de redacción.'],
      ['Investigación', 'Más preguntas. Menos preparación.', 'Abre encuestas y microdatos, consulta etiquetas de SPSS y estudia relaciones entre variables.'],
      ['Producto y operaciones', 'Una explicación para ese cambio.', 'Cruza exportaciones, examina segmentos y convierte una pregunta del equipo en algo que se pueda ver.'],
    ],
    localKicker: 'HECHO PARA TU MAC. Y PARA TUS DATOS.',
    localTitle: 'Tu fichero.<br>Tu ordenador.<br><em>Tu descubrimiento.</em>',
    localText: 'Abre y explora archivos locales sin subirlos a un servidor ni crear una cuenta. Tus vistas y resultados se guardan en tu Mac.',
    localAi: 'Si decides usar IA, tú eliges los campos y el alcance que se envían al proveedor. Abrir un fichero no activa la IA.',
    faqTitle: 'Antes de abrir<br><em>el próximo fichero.</em>',
    faqs: [
      ['¿Qué archivos puedo abrir?', 'CSV, Excel (.xlsx), Parquet y SPSS (.sav). Puedes tener varios archivos y hojas de Excel en un mismo espacio de trabajo. También puedes abrir archivos desde una URL.'],
      ['¿Necesito saber programar?', 'Puedes explorar variables, aplicar filtros y crear gráficos desde la interfaz. Las consultas y fórmulas SQL están disponibles cuando necesitas ir más allá.'],
      ['¿Qué pasa con los archivos grandes?', 'El motor nativo consulta los datos y la tabla muestra páginas de filas y columnas. El análisis puede usar una muestra o el conjunto completo. La primera importación de un CSV o Excel puede tardar; el rendimiento depende del archivo y de tu Mac.'],
      ['¿Se suben mis datos a algún sitio?', 'La exploración de archivos locales se ejecuta en tu Mac. Las fuentes remotas se consultan en su servidor. Si activas un enriquecimiento o análisis con IA, el proveedor recibe el contexto seleccionado para esa operación. Tus claves se guardan en el Llavero de macOS.'],
      ['¿En qué Mac funciona?', 'Esta beta está preparada para Mac con Apple Silicon (M1 o posterior), con macOS 12 o posterior. No ofrecemos todavía una descarga para Mac Intel, Windows o Linux.'],
      ['¿Cuánto cuesta? ¿Está en la App Store?', 'La beta se puede descargar sin crear una cuenta. Está firmada y notarizada por Apple. La IA opcional necesita tu propia clave y puede generar costes en el proveedor. La versión de la Mac App Store está en preparación y todavía no se ha enviado a revisión.'],
    ],
    finalKicker: 'TIENES LOS DATOS. SIGUE TU CURIOSIDAD.',
    finalTitle: 'Ábrelo.<br><em>A ver qué descubres.</em>',
    footerNote: 'Una herramienta de Victoriano Izquierdo.', privacy: 'Privacidad', support: 'Ayuda', releaseNotes: 'Descarga y requisitos',
    downloadTitle: 'Tu próximo hallazgo<br>empieza <em>aquí.</em>',
    downloadIntro: 'Datolens para Mac · beta 0.1.0',
    downloadBeta: 'Descargar beta para Apple Silicon',
    downloadRequirements: 'Mac con chip M1 o posterior · macOS 12 o posterior',
    betaHeading: 'Una beta temprana, para explorar.',
    betaText: 'Firmada con Developer ID y notarizada por Apple. Datolens está en beta: puedes explorar tus archivos sin crear una cuenta y contarnos qué mejorarías.',
    installTitle: 'Instalación',
    installSteps: ['Descarga y descomprime el archivo ZIP.', 'Arrastra Datolens a la carpeta Aplicaciones.', 'Abre Datolens y elige un fichero CSV, Excel, Parquet o SPSS.'],
    installHelp: 'Consulta la información de Apple sobre abrir apps en el Mac.',
    storeTitle: 'Mac App Store', storeState: 'En preparación · todavía no enviada a revisión',
    storeText: 'Estamos preparando la versión de la Mac App Store. Mientras tanto, puedes instalar la beta notarizada desde esta página. Publicaremos aquí el enlace de la tienda cuando esté disponible.',
    checksum: 'Verificar la descarga (SHA-256)',
    supportTitle: 'Un poco de ayuda.<br><em>Y a explorar.</em>',
    supportIntro: 'Datolens está en beta. Estas son las respuestas para empezar y la forma de contarnos qué falla.',
    helpItems: [
      ['Abrir un archivo', 'Usa el botón + del espacio de trabajo para elegir un CSV, XLSX, Parquet o SAV de tu ordenador. Para archivos grandes, deja terminar la importación inicial.'],
      ['Explorar y crear un gráfico', 'En Explorar puedes consultar variables y combinar filtros. Abre la vista de gráficos y elige las variables de los ejes. Los filtros se comparten con el conjunto de datos.'],
      ['Volver a tu trabajo', 'Las vistas y los resultados se guardan localmente. Mantén el archivo original en su ubicación para poder reabrirlo.'],
      ['Funciones de IA', 'Son opcionales. Añade tu propia clave en la configuración, elige el contexto y revisa el alcance antes de ejecutar. La exploración normal funciona sin una clave.'],
      ['Informar de un problema', 'Cuéntanos qué versión de macOS usas, el formato y tamaño del fichero, y los pasos para reproducirlo. No envíes claves API ni datos personales o confidenciales.'],
    ],
    contact: 'Contactar con Victoriano',
    privacyTitle: 'Tus datos,<br><em>en su sitio.</em>',
    privacyIntro: 'Privacidad de Datolens y de esta web · actualizado el 23 de septiembre de 2026.',
    privacyItems: [
      ['Exploración local', 'Datolens procesa en tu Mac los archivos locales que abres. No es necesario crear una cuenta. El archivo original se mantiene y la app guarda vistas, cachés y resultados en el almacenamiento local de la aplicación; algunas preferencias se guardan junto al archivo.'],
      ['Fuentes remotas', 'Al abrir una URL, Datolens se conecta al servidor de origen. Ese servidor puede recibir tu dirección IP y los datos habituales de la petición. Algunos Parquet se consultan por rangos; otras fuentes se descargan para trabajar con una copia local.'],
      ['IA opcional', 'Las funciones de IA envían al proveedor elegido el prompt, los campos, muestras u otro contexto seleccionado que necesita la operación. No se activa IA al abrir un archivo. El proveedor trata esa información según sus propias condiciones y política de privacidad. Revisa el alcance antes de ejecutar y evita enviar información que no quieras compartir.'],
      ['Claves y almacenamiento', 'Las claves API se guardan en el Llavero de macOS. Las vistas, resultados y cachés permanecen en tu Mac. Puedes retirar las claves desde la configuración y eliminar los archivos locales cuando dejen de ser necesarios.'],
      ['Esta web', 'Esta web no incorpora herramientas de analítica, cookies publicitarias ni formularios de seguimiento. Las fuentes se sirven desde el mismo sitio. El proveedor de alojamiento, Vercel, puede procesar información técnica de las peticiones, como direcciones IP, para servir y proteger la web.'],
      ['Contacto', 'Datolens es un proyecto de Victoriano Izquierdo. Para consultas sobre privacidad o datos compartidos al pedir soporte, utiliza el enlace de contacto. Incluye solo la información necesaria para atender tu solicitud.'],
    ],
  },
  en: {
    lang: 'en', locale: 'en_US', path: '/en', other: '/', otherLabel: 'Español',
    title: 'Datolens — Big files. Clear thinking.',
    description: 'Open large CSV, Excel, Parquet and SPSS files on your Mac. Explore variables, connect filters and build charts to understand your data. Download the Datolens beta.',
    skip: 'Skip to content', explore: 'The product', people: 'Who it’s for', questions: 'Questions', download: 'Download for Mac',
    eyebrow: 'CURIOSITY, IN ITS ELEMENT',
    hero: 'Big files.<br>Clear <em>thinking.</em>',
    intro: 'That enormous file has something to tell you. <br>Open it, explore it, find the story. Right on your Mac.',
    watch: 'See the product', release: 'BETA 0.1 · MACOS · APPLE SILICON',
    demoLabel: 'Real Datolens screenshots · sample data', demoFile: 'housing_demo.csv',
    demoHint: 'Table, exploration and charts.', all: 'All cities', cities: ['Madrid', 'Barcelona', 'Valencia', 'Sevilla'],
    rows: 'rows', vars: 'variables', table: 'Table', distribution: 'Explore', chart: 'Chart',
    stepTitles: ['Open the file.', 'Follow a clue.', 'Make it visible.'],
    stepSubtitles: ['Start with what you have.', 'Connect filters and variables.', 'From a question to a chart.'],
    demoXAxis: 'Floor area · m²', demoYAxis: 'Price · €', demoBarTitle: 'Average price by city',
    demoFields: ['City', 'Floor area', 'Price', 'Bedrooms'],
    demoVariables: 'Your variables, at a glance', demoNote: 'Filter by city and watch the data change.',
    play: 'Resume animation', pause: 'Pause animation',
    formatKicker: 'YOUR EVERYDAY FILES. A FRESH WAY TO SEE THEM.',
    statementKicker: 'LESS SETUP. MORE DISCOVERY.',
    statement: 'You came to understand the data.<br><span>Start right there.</span>',
    features: [
      { n: '01', title: 'The big picture.<br>Every little detail.', text: 'Hundreds of variables don’t have to mean hundreds of unknowns. Scan distributions, spot missing values and find what stands out.', tag: 'DISTRIBUTIONS · STATISTICS · TYPES' },
      { n: '02', title: 'One question.<br>The next clue.', text: 'Select a range, filter a category, see what changes everywhere else. Explore relationships without losing your train of thought across sheets and files.', tag: 'CONNECTED FILTERS · MULTIPLE FILES' },
      { n: '03', title: 'From “I think”<br>to “look at this”.', text: 'Bar charts, scatter plots, time series and pivot tables. Choose your variables, find an angle and export a chart for your next report.', tag: 'CHARTS · PNG, SVG & CSV EXPORTS' },
    ],
    scaleKicker: 'FOR FILES WITH A LOT TO SAY',
    scaleTitle: 'Room for your data.<br><em>Space to think.</em>',
    scaleText: 'Millions of rows. Thousands of variables. Datolens uses a local data engine and displays what you need to explore. Get your bearings with a sample, then dig deeper with the full dataset.',
    scaleNote: 'Opening time depends on the format, size and your Mac. CSV and Excel require an initial import.',
    scaleLegend: ['One row. One possibility.', 'Explore a sample or the full dataset.'],
    peopleKicker: 'FOR PEOPLE WITH ONE MORE QUESTION',
    peopleTitle: 'The next discovery<br>could be <em>yours.</em>',
    peopleItems: [
      ['Data analysts', 'That fresh export in your inbox.', 'Inspect a file, check distributions and find the variables worth a closer look.'],
      ['Data journalists', 'The story between the rows.', 'Explore public datasets, compare groups and bring a chart to your next editorial meeting.'],
      ['Researchers', 'More questions. Less preparation.', 'Open surveys and microdata, read SPSS labels and investigate relationships between variables.'],
      ['Product & operations', 'An explanation for that change.', 'Work across exports, inspect segments and turn a team question into something you can see.'],
    ],
    localKicker: 'MADE FOR YOUR MAC. AND YOUR DATA.',
    localTitle: 'Your file.<br>Your computer.<br><em>Your discovery.</em>',
    localText: 'Open and explore local files without uploading them to a server or creating an account. Your views and results stay on your Mac.',
    localAi: 'If you choose to use AI, you select the fields and scope sent to the provider. Opening a file never turns AI on.',
    faqTitle: 'Before you open<br><em>the next file.</em>',
    faqs: [
      ['Which files can I open?', 'CSV, Excel (.xlsx), Parquet and SPSS (.sav). Work with several files and Excel sheets in one workspace. You can also open files from a URL.'],
      ['Do I need to code?', 'Explore variables, apply filters and create charts through the interface. SQL queries and formulas are available when you want to go further.'],
      ['How does it handle large files?', 'A native engine queries the data, while the table displays pages of rows and columns. Analysis can use a sample or the full dataset. The first CSV or Excel import may take time; performance depends on the file and your Mac.'],
      ['Does my data get uploaded?', 'Local file exploration runs on your Mac. Remote sources are requested from their server. If you enable AI enrichment or analysis, the provider receives the selected context for that operation. API keys are stored in macOS Keychain.'],
      ['Which Macs are supported?', 'This beta is built for Apple Silicon Macs (M1 or later), running macOS 12 or later. There is no Intel Mac, Windows or Linux download yet.'],
      ['What does it cost? Is it on the App Store?', 'You can download the beta without creating an account. It is signed and notarized by Apple. Optional AI needs your own API key and may incur provider charges. The Mac App Store version is in preparation and has not been submitted for review.'],
    ],
    finalKicker: 'YOU HAVE THE DATA. FOLLOW YOUR CURIOSITY.',
    finalTitle: 'Open it.<br><em>See what you find.</em>',
    footerNote: 'A tool by Victoriano Izquierdo.', privacy: 'Privacy', support: 'Support', releaseNotes: 'Download & requirements',
    downloadTitle: 'Your next discovery<br>starts <em>here.</em>',
    downloadIntro: 'Datolens for Mac · beta 0.1.0',
    downloadBeta: 'Download beta for Apple Silicon',
    downloadRequirements: 'Mac with M1 or later · macOS 12 or later',
    betaHeading: 'An early beta, built for exploring.',
    betaText: 'Signed with Developer ID and notarized by Apple. Datolens is in beta: explore your files without creating an account, and tell us what you would improve.',
    installTitle: 'Installation',
    installSteps: ['Download and unzip the ZIP archive.', 'Drag Datolens into Applications.', 'Open Datolens and choose a CSV, Excel, Parquet or SPSS file.'],
    installHelp: 'Read Apple’s information about opening apps on your Mac.',
    storeTitle: 'Mac App Store', storeState: 'In preparation · not yet submitted for review',
    storeText: 'We are preparing the Mac App Store version. In the meantime, install the notarized beta from this page. We will add the store link here when it is available.',
    checksum: 'Verify the download (SHA-256)',
    supportTitle: 'A little help.<br><em>Then, explore.</em>',
    supportIntro: 'Datolens is in beta. Here is how to get started and tell us when something goes wrong.',
    helpItems: [
      ['Open a file', 'Use the + button in the workspace to choose a CSV, XLSX, Parquet or SAV file from your computer. Allow the initial import to finish for large files.'],
      ['Explore and create a chart', 'Use Explore to inspect variables and combine filters. Open the chart view and choose your axis variables. Filters are shared with the dataset.'],
      ['Return to your work', 'Views and results are saved locally. Keep the original file in its location so you can reopen it.'],
      ['AI features', 'These are optional. Add your own key in settings, choose the context and review the scope before running. Regular exploration works without a key.'],
      ['Report a problem', 'Tell us your macOS version, the file format and size, and steps to reproduce the problem. Do not send API keys or personal or confidential data.'],
    ],
    contact: 'Contact Victoriano',
    privacyTitle: 'Your data,<br><em>where it belongs.</em>',
    privacyIntro: 'Privacy for Datolens and this website · updated September 23, 2026.',
    privacyItems: [
      ['Local exploration', 'Datolens processes the local files you open on your Mac. No account is required. The original file is kept intact. Views, caches and results are saved in local application storage; some preferences are saved alongside the file.'],
      ['Remote sources', 'When you open a URL, Datolens connects to its origin server. That server may receive your IP address and standard request information. Some Parquet files are queried by byte range; other sources are downloaded to a local copy.'],
      ['Optional AI', 'AI features send the chosen provider the prompt, fields, samples or other selected context needed for the operation. Opening a file does not turn AI on. Providers process this information under their own terms and privacy policies. Review the scope before running and avoid sending information you do not want to share.'],
      ['Keys and storage', 'API keys are stored in macOS Keychain. Views, results and caches remain on your Mac. You can remove keys in settings and delete local files when no longer needed.'],
      ['This website', 'This website includes no analytics tools, advertising cookies or tracking forms. Fonts are served from this site. Our host, Vercel, may process technical request information such as IP addresses to serve and protect the website.'],
      ['Contact', 'Datolens is a project by Victoriano Izquierdo. For privacy questions or information shared in a support request, use the contact link. Include only the information necessary to handle your request.'],
    ],
  },
};
