import { VariablePicker, VariableChecklist } from '../../ui/VariablePicker';
import { t, useI18n, getUiSnapshot } from '../../ui';
import { useEffect, useState } from 'react';
import { CHARTS, changeAxisVariable, hasColor, isArea, isLine, isPoints, statisticOptions } from './model';
import type { Column, PlotConfig, Annotation } from './types';

interface Props { config: PlotConfig; columns: Column[]; categories: string[]; onChange(config: PlotConfig): void }
function NumberField({label,value,min,max,step,onChange}:{label:string;value:number;min?:number;max?:number;step?:number;onChange(value:number):void}){
  const [draft,setDraft]=useState<string|null>(null);
  useEffect(()=>setDraft(null),[value]);
  return <label className="dl-plot-field"><span>{label}</span><input aria-label={label} type="number" value={draft??String(value)} min={min} max={max} step={step} onChange={e=>{
    const raw=e.target.value;
    setDraft(raw);
    if(raw.trim()==='')return;
    const next=Number(raw);
    if(Number.isFinite(next)&&(min===undefined||next>=min)&&(max===undefined||next<=max))onChange(next);
  }} onBlur={()=>setDraft(null)}/></label>;
}
export function PlotSettings({config:c,columns,categories,onChange}:Props){
  const [tab,setTab]=useState<'data'|'appearance'|'annotations'>('data');
  const update=(patch:Partial<PlotConfig>)=>onChange({...c,...patch,...(patch.theme?{background:patch.theme==='dark'?'#202223':patch.theme==='paper'?'#faf8f1':'#ffffff'}:{})});
  const field=(key:keyof PlotConfig,label:string,kind:'text'|'number'|'color'='text',min?:number,max?:number,step?:number)=>kind==='number'?<NumberField key={key} label={label} value={Number(c[key])} min={min} max={max} step={step} onChange={value=>update({[key]:value})}/>:<label className="dl-plot-field" key={key}><span>{label}</span><input aria-label={label} type={kind} value={String(c[key]??'')} onChange={e=>update({[key]:e.target.value})}/></label>;
  const toggle=(key:keyof PlotConfig,label:string)=><label className="dl-plot-toggle" key={key}><input type="checkbox" checked={!!c[key]} onChange={e=>update({[key]:e.target.checked})}/><span>{label}</span></label>;
  const select=(key:keyof PlotConfig,label:string,options:ReadonlyArray<readonly [string,string]>)=><label className="dl-plot-field" key={key}><span>{label}</span><select aria-label={label} value={String(c[key]??'')} onChange={e=>update({[key]:e.target.value})}>{options.map(([value,name])=><option key={value} value={value}>{t(name)}</option>)}</select></label>;
  const column=(key:'x'|'y'|'color'|'size'|'cell',label:string,numeric=false,allowEmpty=true)=><div className="dl-plot-field"><span>{label}</span><VariablePicker label={label} columns={columns.filter(col=>!numeric||col.kind==='numeric')} value={c[key]} placeholder={t("Selecciona una variable…")} emptyLabel={allowEmpty?(key==='y'||key==='cell'?t("Número de filas"):t("Sin variable")):undefined} onChange={id=>{
    const col=columns.find(item=>item.id===id);
    if(key==='x'||key==='y'){onChange(changeAxisVariable(c,columns,key,id));return;}
    update({[key]:id,...(key==='cell'?{stat:id&&c.stat==='count'?(col?.kind==='numeric'?'mean':'valid'):id?c.stat:'count'}:{})});
  }}/></div>;
  const multiselect=(key:'tableRows'|'tableColumns'|'tableValues'|'multipleY'|'tooltipColumns',label:string,numeric=false)=><fieldset className="dl-plot-multi"><legend>{label}</legend><VariableChecklist label={label} columns={columns.filter(col=>!numeric||col.kind==='numeric')} value={c[key]} onChange={ids=>update({[key]:ids})}/></fieldset>;
  const dateOptions=[['hour',t("Hora")],['day',t("Día")],['week',t("Semana")],['month',t("Mes")],['quarter',t("Trimestre")],['year',t("Año")]] as const;
  const bins=(slot:'x'|'y'|'color',id:string)=>{
    const col=columns.find(col=>col.id===id);if(!col)return null;
    return <div className="dl-plot-control-group"><h4>{t("Agrupar ")}{slot==='color'?'color':slot.toUpperCase()}</h4>{col.kind==='date'?<>{select(slot==='x'?'interval':slot==='y'?'intervalY':'intervalColor',t("Periodo ")+slot,dateOptions)}{slot==='x'&&select('dateComponent',t("Componente de fecha"),[['',t("Fecha completa")],['year',t("Año")],['quarter',t("Trimestre")],['month',t("Mes del año")],['dayofweek',t("Día de la semana (0 = domingo)")],['hour',t("Hora del día")]])}</>:col.kind==='numeric'?<>{select(slot==='x'?'xBinning':slot==='y'?'yBinning':'colorBinning',t("Agrupación ")+slot,[['width',t("Intervalos iguales")],['quantile',t("Cuantiles")],['exact',t("Valores exactos")]])}{field(slot==='x'?'bins':slot==='y'?'binsY':'binsColor',t("Número de intervalos ")+slot,'number',1,100,1)}</>:<small>{t("Valores exactos")}</small>}</div>;
  };
  const annotationChange=(id:string,patch:Partial<Annotation>)=>update({annotations:c.annotations.map(a=>a.id===id?{...a,...patch}:a)});
  return <aside className="dl-plot-settings" aria-label={t("Configuración del gráfico")}><header><strong>{t("Configuración")}</strong></header><div className="dl-plot-settings-tabs" role="tablist">{([['data',t("Datos")],['appearance',t("Diseño")],['annotations',t("Anotaciones")]] as const).map(([id,name])=><button key={id} role="tab" aria-selected={tab===id} onClick={()=>setTab(id)}>{name}</button>)}</div>
    <div className="dl-plot-settings-scroll" role="tabpanel">
    {tab==='data'&&<>
      <section><h4>{t("Variables")}</h4>{c.kind==='table'?<>{multiselect('tableRows',t("Filas"))}{multiselect('tableColumns',t("Columnas"))}{multiselect('tableValues',t("Medidas"))}</>:<>{column('x',t("Eje X"),isPoints(c.kind),false)}{c.kind==='multipleLine'?multiselect('multipleY',t("Medidas Y"),true):column('y',t("Eje Y"),isPoints(c.kind)||c.kind==='box',!(isPoints(c.kind)||c.kind==='box'||c.kind==='heatmap'))}{c.kind==='heatmap'&&column('cell',t("Medida de las celdas"))}{hasColor(c.kind)&&column('color',t("Color / segmento"))}{c.kind.toLowerCase().includes('bubble')&&column('size',t("Tamaño"),true,false)}</>}</section>
      {!isPoints(c.kind)&&c.kind!=='box'&&<section><h4>{t("Agregación")}</h4>{['heatmap','multipleLine','table'].includes(c.kind)&&<>{select('stat',t("Estadístico"),statisticOptions(c))}{c.stat==='percentile'&&field('percentile',t("Percentil (0–100)"),'number',0,100,.1)}{['countWhere','percentWhere'].includes(c.stat)&&field('statisticValue',t("Valor que contar"))}</>}{toggle('includeMissing',t("Incluir grupos vacíos"))}<small>{t("Calculado sobre todas las filas filtradas.")}</small></section>}
      {!isPoints(c.kind)&&<section>{bins('x',c.x)}{c.kind==='heatmap'&&bins('y',c.y)}{hasColor(c.kind)&&bins('color',c.color)}<small>{t("Cuantiles con interpolación lineal; los empates permanecen juntos. Fechas en UTC.")}</small></section>}
      {!isPoints(c.kind)&&<section><h4>{t("Orden")}</h4>{select('sort',t("Ordenar por"),[['natural',t("Variable")],['value',t("Valor")],['count',t("Número de filas")]])}{toggle('descending',t("Orden descendente"))}{c.kind==='heatmap'&&<>{select('sortY',t("Ordenar eje Y por"),[['natural',t("Variable")],['value',t("Valor")],['count',t("Número de filas")]])}{toggle('descendingY',t("Eje Y descendente"))}</>}</section>}
      <section><h4>{t("Interacción")}</h4>{toggle('linkFilters',t("Conectar con los filtros de la tabla"))}{isPoints(c.kind)&&<small>{t("Mayúsculas + arrastrar selecciona un intervalo en ambos ejes.")}</small>}</section>
      {isPoints(c.kind)&&<section><h4>{t("Relación")}</h4>{toggle('correlation',t("Mostrar correlación de Pearson"))}{toggle('regression',t("Recta de regresión"))}{field('pointMin',t("Tamaño mínimo (px)"),'number',1,30,1)}{field('pointMax',t("Tamaño máximo (px)"),'number',1,100,1)}<small>{t("La correlación y la recta usan todos los pares válidos filtrados.")}</small></section>}
      {c.kind==='seasonal'&&<section><h4>{t("Descomposición")}</h4>{field('period',t("Intervalos por ciclo"),'number',2,365,1)}{toggle('sharedSeasonalScale',t("Misma escala en estacionalidad y residuo"))}<small>{t("Modelo aditivo con media móvil centrada. Requiere al menos dos ciclos y periodos consecutivos.")}</small></section>}
    </>}
    {tab==='appearance'&&<>
      <section><h4>{t("Textos del gráfico")}</h4>{toggle('showTitle',t("Mostrar título"))}{field('title',t("Título"))}{toggle('showSubtitle',t("Mostrar subtítulo"))}{field('subtitle',t("Subtítulo"))}{toggle('showDescription',t("Mostrar descripción"))}{field('description',t("Descripción"))}{toggle('showFooter',t("Mostrar pie"))}{field('footer',t("Pie de gráfico"))}</section>
      <section><h4>{t("Color")}</h4>{select('theme',t("Tema"),[['light',t("Claro")],['dark',t("Oscuro")],['paper',t("Papel")]])}{field('background',t("Fondo"),'color')}{field('singleColor',t("Color principal"),'color')}{select('palette',t("Paleta"),[['tableau10',t("Categórica")],['category10',t("Contraste")],['blues',t("Azules")],['viridis',t("Viridis")],['magma',t("Magma")],['redblue',t("Divergente")]])}{toggle('reversePalette',t("Invertir paleta"))}{toggle('legend',t("Mostrar leyenda"))}{field('opacity',t("Opacidad"),'number',.05,1,.05)}{categories.slice(0,30).map(category=><label className="dl-plot-field" key={category}><span title={category}>{category}</span><input type="color" aria-label={t("Color de ")+category} value={c.categoryColors[category]??c.singleColor} onChange={e=>update({categoryColors:{...c.categoryColors,[category]:e.target.value}})}/></label>)}{Object.keys(c.categoryColors).length>0&&<button onClick={()=>update({categoryColors:{}})}>{t("Restablecer colores")}</button>}</section>
      {c.kind!=='table'&&<section><h4>{t("Etiquetas")}</h4>{toggle('labels',t("Mostrar valores"))}{select('numberFormat',t("Formato de valores"),[[',.2f','1.234,56'],[',.0f','1.235'],['.1%','12,3 %'],['~s','1,2k'],['.3e','1,234e+3']])}{toggle('showCount',t("Mostrar recuento"))}{toggle('showChange',t("Mostrar variación porcentual"))}{toggle('showTotals',t("Mostrar totales"))}{select('labelPosition',t("Posición"),[['outside',t("Exterior")],['inside',t("Interior")]])}{select('labelAlign',t("Alineación"),[['left',t("Izquierda")],['center',t("Centro")],['right',t("Derecha")]])}{toggle('tooltip',t("Información al pasar el cursor"))}{isPoints(c.kind)&&multiselect('tooltipColumns',t("Campos adicionales"))}</section>}
      {c.kind!=='table'&&(['x','y'] as const).map(axis=>{
        const key=axis==='x'?'xAxis':'yAxis',a=c[key];
        const patch=(value:Partial<typeof a>)=>update({[key]:{...a,...value}});
        const dateAxis=columns.find(col=>col.id===(axis==='x'?c.x:c.y))?.kind==='date';
        const formats=dateAxis?['auto','%b %Y','%d/%m/%Y','%m/%Y','%m','%Y','%H:%M','%H:%M:%S']:['auto','~s',',.0f',',.1f',',.2f',',','.0%','.1%','.2%','.2e'];
        return <section key={axis}><h4>{t("Eje ")}{axis.toUpperCase()}</h4><label className="dl-plot-toggle"><input type="checkbox" checked={a.showTitle} onChange={e=>patch({showTitle:e.target.checked})}/>{t("Mostrar título del eje")}</label><label className="dl-plot-field"><span>{t("Título del eje ")}{axis.toUpperCase()}</span><input value={a.title} placeholder={t("Nombre de la variable")} onChange={e=>patch({title:e.target.value})}/></label>
          {(['log','zero','grid'] as const).map((k,i)=><label className="dl-plot-toggle" key={k}><input type="checkbox" checked={a[k]} onChange={e=>patch({[k]:e.target.checked})}/>{[t("Escala logarítmica"),t("Incluir cero"),t("Mostrar cuadrícula")][i]}</label>)}
          <div className="dl-plot-pair">{(['min','max'] as const).map(k=><label key={k}><span>{k==='min'?t("Mínimo"):t("Máximo")}</span><input type="number" aria-label={`${axis.toUpperCase()} ${k}`} value={a[k]??''} placeholder={t("Auto")} onChange={e=>patch({[k]:e.target.value===''?undefined:Number(e.target.value)})}/></label>)}</div>
          <label className="dl-plot-field"><span>{t("Formato del eje ")}{axis.toUpperCase()}</span><select value={formats.includes(a.format)?a.format:'custom'} onChange={e=>patch({format:e.target.value==='custom'?(dateAxis?'%d %b %Y':',.3f'):e.target.value})}>{formats.map(format=><option key={format} value={format}>{format==='auto'?t("Automático"):format}</option>)}<option value="custom">{t("Personalizado…")}</option></select></label>
          {axis==='x'&&columns.find(col=>col.id===c.x)?.kind==='numeric'&&c.xBinning!=='exact'&&!isPoints(c.kind)&&!isLine(c.kind)&&!isArea(c.kind)&&<label className="dl-plot-field"><span>{t("Etiquetas de intervalos")}</span><select aria-label={t("Etiquetas de intervalos")} value={a.binLabel??'end'} onChange={e=>patch({binLabel:e.target.value as NonNullable<typeof a.binLabel>})}><option value="range">{t("Rango completo")}</option><option value="start">{t("Inicio del intervalo")}</option><option value="end">{t("Final del intervalo")}</option></select></label>}
          {!formats.includes(a.format)&&<label className="dl-plot-field"><span>{t("Formato personalizado (D3)")}</span><input value={a.format} onChange={e=>patch({format:e.target.value})}/></label>}
          <label className="dl-plot-field"><span>{t("Marcas del eje ")}{axis.toUpperCase()}</span><input type="number" min={2} max={40} value={a.ticks} onChange={e=>patch({ticks:Math.max(2,Math.min(40,Number(e.target.value)))})}/></label>
          <label className="dl-plot-field"><span>{t("Marcas personalizadas ")}{axis.toUpperCase()}</span><input value={a.customTicks} placeholder={t("0,10,20")} onChange={e=>patch({customTicks:e.target.value})}/></label>
          <label className="dl-plot-field"><span>{t("Rotación ")}{axis.toUpperCase()}</span><input type="number" min={-90} max={90} value={a.rotation} onChange={e=>patch({rotation:Number(e.target.value)})}/></label>
          <label className="dl-plot-field"><span>{t("Separación mínima entre etiquetas (px)")}</span><input type="number" min={0} max={40} value={a.labelSeparation??6} onChange={e=>patch({labelSeparation:Math.max(0,Math.min(40,Number(e.target.value)))})}/></label>
          <label className="dl-plot-field"><span>{t("Ancho de etiquetas ")}{axis.toUpperCase()}</span><input type="number" min={20} max={500} value={a.labelWidth} onChange={e=>patch({labelWidth:Math.max(20,Number(e.target.value))})}/></label>
        </section>;
      })}
      {(isLine(c.kind)||isArea(c.kind))&&<section><h4>{t("Líneas y áreas")}</h4>{select('interpolation',t("Interpolación"),[['linear',t("Lineal")],['monotone',t("Suave")],['step',t("Escalones")],['basis',t("Spline")]])}{field('lineWidth',t("Grosor"),'number',.5,12,.5)}{toggle('dashed',t("Trazo discontinuo"))}{toggle('markers',t("Mostrar puntos"))}{select('missing',t("Valores vacíos"),[['gap',t("Dejar hueco")],['zero',t("Cero")],['connect',t("Conectar")]])}{toggle('zerosMissing',t("Tratar ceros como vacíos"))}</section>}
      {CHARTS.find(chart=>chart.kind===c.kind)?.family==='bar'&&<section><h4>{t("Barras")}</h4>{toggle('horizontal',t("Orientación horizontal"))}{field('innerPadding',t("Espacio entre barras"),'number',0,.9,.05)}{field('outerPadding',t("Margen exterior"),'number',0,1,.05)}</section>}
      {c.kind==='box'&&<section><h4>{t("Diagrama de caja")}</h4>{select('boxStyle',t("Estadísticas de caja"),[['quartiles',t("Cuartiles")],['iqr',t("Cuartiles + 1,5 IQR")],['extent',t("Cuartiles + mínimo y máximo")],['deviation',t("Media ± desviación estándar")]])}{toggle('horizontal',t("Orientación horizontal"))}</section>}
      {c.kind==='table'&&<section><h4>{t("Tabla dinámica")}</h4>{field('pageSize',t("Filas por página"),'number',5,200,5)}{toggle('hideIndex',t("Ocultar índice"))}{toggle('showTotals',t("Mostrar totales"))}{select('cellStyle',t("Estilo de las celdas"),[['plain',t("Texto")],['heat',t("Mapa de calor")],['bars',t("Barras")]])}{select('numberFormat',t("Formato numérico"),[[',.2f',t("2 decimales")],[',.0f',t("Enteros")],['.1%',t("Porcentaje")],['~s',t("Abreviado")]])}</section>}
      <section><h4>{t("Tamaño")}</h4>{field('height',t("Alto (px)"),'number',200,1600,10)}<label className="dl-plot-field"><span>{t("Ancho (px)")}</span><input type="number" min={360} max={2400} value={c.width??''} placeholder={t("Automático")} onChange={e=>update({width:e.target.value?Math.max(360,Math.min(2400,Number(e.target.value))):undefined})}/></label><button onClick={()=>update({width:undefined,height:430})}>{t("Ajustar a la ventana")}</button></section>
    </>}
    {tab==='annotations'&&<><section><h4>{t("Marcas de referencia")}</h4><p>{t("Añade líneas, intervalos o texto sobre el gráfico.")}</p><div className="dl-plot-annotation-actions">{(['x','y','text'] as const).map(kind=><button key={kind} onClick={()=>update({annotations:[...c.annotations,{id:crypto.randomUUID(),kind,value:0,label:kind==='text'?t("Nota"):'',x:.1,y:.1,color:c.singleColor}]})}>+ {kind==='text'?t("Texto"):t("Eje {value0}", {value0: kind.toUpperCase()})}</button>)}</div></section>
      {c.annotations.map((a,index)=><section className="dl-plot-annotation" key={a.id}><header><strong>{a.kind==='text'?t("Texto"):t("Marca {value0}", {value0: a.kind.toUpperCase()})} {index+1}</strong><button aria-label={t("Eliminar anotación {value0}", {value0: index+1})} onClick={()=>update({annotations:c.annotations.filter(item=>item.id!==a.id)})}>{t("×")}</button></header><label className="dl-plot-field"><span>{t("Etiqueta ")}{index+1}</span><input value={a.label} onChange={e=>annotationChange(a.id,{label:e.target.value})}/></label>{a.kind==='text'?<div className="dl-plot-pair">{(['x','y'] as const).map(key=><label key={key}><span>{key.toUpperCase()} (0–1)</span><input type="number" min={0} max={1} step={.05} value={a[key]} onChange={e=>annotationChange(a.id,{[key]:Math.max(0,Math.min(1,Number(e.target.value)))})}/></label>)}</div>:<><label className="dl-plot-field"><span>{t("Valor ")}{index+1}</span><input type="number" value={a.value} onChange={e=>annotationChange(a.id,{value:Number(e.target.value)})}/></label><label className="dl-plot-field"><span>{t("Hasta (opcional)")}</span><input type="number" value={a.end??''} onChange={e=>annotationChange(a.id,{end:e.target.value===''?undefined:Number(e.target.value)})}/></label></>}<label className="dl-plot-field"><span>{t("Color de la anotación")}</span><input type="color" value={a.color} onChange={e=>annotationChange(a.id,{color:e.target.value})}/></label></section>)}
    </>}
    </div>
  </aside>;
}
