//! A disposable, disk-backed SQL workspace. Only explicitly supplied snapshots are loaded.
use crate::{sql::{ident,literal}, Error, Result};
use duckdb::Connection;
use std::{collections::HashSet, path::{Path,PathBuf}, sync::mpsc, time::Duration};

pub const MAX_RESULT_ROWS: u64 = 1_000_000;

/// Reject statement separators even inside literals: a deliberately conservative SQL surface.
/// The subquery wrapper then lets DuckDB's parser enforce a read-only query expression.
fn query_expression(sql: &str) -> Result<&str> {
    let sql=sql.trim().trim_end_matches(';').trim();
    if sql.is_empty() || sql.len()>100_000 || sql.contains(';') || sql.contains('\0') {
        return Err(Error::Invalid("Escribe una única consulta SELECT o WITH, sin separadores ; internos.".into()));
    }
    let first=sql.split(|c:char| !c.is_ascii_alphabetic()).next().unwrap_or("");
    if !first.eq_ignore_ascii_case("select") && !first.eq_ignore_ascii_case("with") {
        return Err(Error::Invalid("Solo se admiten consultas SELECT o WITH.".into()));
    }
    Ok(sql)
}

/// Bind an AI proposal against empty tables: validates columns and SQL without reading rows.
pub fn validate_query_schema(tables: &[(String,Vec<crate::Column>)], sql: &str) -> Result<()> {
    let sql=query_expression(sql)?;
    let conn=Connection::open_in_memory()?;
    conn.execute_batch("SET memory_limit='128MB'; SET threads=1; SET autoinstall_known_extensions=false; SET autoload_known_extensions=false; SET enable_external_access=false; SET lock_configuration=true;")?;
    for (alias,columns) in tables {
        let fields=columns.iter().map(|column|format!("{} {}",ident(&column.id),column.data_type)).collect::<Vec<_>>().join(",");
        conn.execute_batch(&format!("CREATE TABLE {} ({fields})",ident(alias)))?;
    }
    conn.prepare(&format!("SELECT * FROM (\n{sql}\n) proposed_query LIMIT 0"))?;
    Ok(())
}

/// Input paths and output path are generated by the host, never interpolated from SQL.
pub fn materialize_query(sources: &[(String,PathBuf)], sql: &str, target: &Path, scratch: &Path) -> Result<()> {
    materialize_with_timeout(sources,sql,target,scratch,Duration::from_secs(30))
}

fn materialize_with_timeout(sources: &[(String,PathBuf)], sql: &str, target: &Path, scratch: &Path, timeout: Duration) -> Result<()> {
    let sql=query_expression(sql)?;
    if sources.is_empty() || sources.len()>32 {return Err(Error::Invalid("Selecciona entre 1 y 32 tablas.".into()));}
    let mut aliases=HashSet::new();
    for (alias,_) in sources {
        if alias.is_empty() || alias.len()>64 || !alias.bytes().all(|b|b.is_ascii_alphanumeric()||b==b'_') || !alias.as_bytes()[0].is_ascii_alphabetic() || alias.eq_ignore_ascii_case("dl_query_result") || !aliases.insert(alias.to_ascii_lowercase()) {
            return Err(Error::Invalid("Los alias deben ser únicos y contener letras, números o guiones bajos.".into()));
        }
    }
    if target.exists() {return Err(Error::Invalid("El resultado ya existe; elige otro nombre.".into()));}
    let database=scratch.join("query.duckdb");
    {
        let conn=Connection::open(&database)?;
        conn.execute_batch("SET memory_limit='512MB'; SET threads=2; SET autoinstall_known_extensions=false; SET autoload_known_extensions=false;")?;
        conn.execute_batch(&format!("SET temp_directory={}",literal(&scratch.join("spill").to_string_lossy())))?;
        for (alias,path) in sources {
            conn.execute_batch(&format!("CREATE TABLE {} AS SELECT * FROM read_parquet({})",ident(alias),literal(&path.to_string_lossy())))?;
        }
        // No filesystem/network access or config changes while evaluating user SQL.
        conn.execute_batch("SET enable_external_access=false; SET lock_configuration=true;")?;
        let interrupt=conn.interrupt_handle();
        let (finished,wait)=mpsc::channel();
        let watchdog=std::thread::spawn(move|| {if matches!(wait.recv_timeout(timeout),Err(mpsc::RecvTimeoutError::Timeout)) {interrupt.interrupt();}});
        let result=conn.execute_batch(&format!("CREATE TABLE dl_query_result AS SELECT * FROM (\n{sql}\n) AS query_result LIMIT {}",MAX_RESULT_ROWS+1));
        let _=finished.send(());let _=watchdog.join();
        result?;
        let count:u64=conn.query_row("SELECT count(*) FROM dl_query_result",[],|r|r.get(0))?;
        if count>MAX_RESULT_ROWS {return Err(Error::Invalid("El resultado supera 1.000.000 de filas. Reduce la consulta o añade LIMIT.".into()));}
    }
    // Fresh connection after the sandbox has closed. Execute only host-owned SQL here.
    let conn=Connection::open(&database)?;
    let parent=target.parent().ok_or_else(||Error::Invalid("Destino sin directorio".into()))?;
    let tmp=tempfile::NamedTempFile::new_in(parent)?;
    conn.execute_batch(&format!("COPY dl_query_result TO {} (FORMAT PARQUET, COMPRESSION ZSTD)",literal(&tmp.path().to_string_lossy())))?;
    tmp.as_file().sync_all()?;
    tmp.persist_noclobber(target).map_err(|e|Error::Io(e.error))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{DataStore,ExportRequest,ExportFormat,PageRequest};
    fn snapshot(dir:&Path,name:&str,csv:&str)->(String,PathBuf) {
        let source=dir.join(format!("{name}.csv"));std::fs::write(&source,csv).unwrap();
        let data=DataStore::open(&source,None,&dir.join("cache")).unwrap();
        let path=dir.join(format!("{name}.parquet"));
        data.export(ExportRequest{path:path.to_string_lossy().into(),format:ExportFormat::Parquet,filters:vec![],sorting:vec![],columns:data.dataset().columns.into_iter().map(|c|c.id).collect()}).unwrap();
        (name.into(),path)
    }
    #[test]
    fn joins_are_durable_independent_datasets_with_exact_ids() {
        let dir=tempfile::tempdir().unwrap();
        let sources=vec![snapshot(dir.path(),"customers","id,name\n9007199254740993,Ana\n9007199254740995,Luis\n"),snapshot(dir.path(),"orders","customer_id,total\n9007199254740993,12\n9007199254740993,8\n")];
        let scratch=tempfile::tempdir().unwrap();let out=dir.path().join("joined.parquet");
        materialize_query(&sources,"WITH totals AS (SELECT customer_id, SUM(total) AS total FROM orders GROUP BY customer_id) SELECT c.id,c.name,t.total FROM customers c LEFT JOIN totals t ON c.id=t.customer_id ORDER BY c.name",&out,scratch.path()).unwrap();
        let data=DataStore::open(&out,None,&dir.path().join("cache")).unwrap();
        let page=data.query_page(PageRequest{dataset_id:data.dataset().id,columns:vec!["id".into(),"name".into(),"total".into()],filters:vec![],sorting:vec![],offset:0,limit:10}).unwrap();
        assert_eq!(page.rows.len(),2);assert_eq!(page.rows[0].values["id"],serde_json::json!("9007199254740993"));assert_eq!(page.rows[0].values["total"],serde_json::json!(20.0));assert!(page.rows[1].values["total"].is_null());
        drop(data);drop(scratch);
        assert_eq!(DataStore::open(&out,None,&dir.path().join("cache2")).unwrap().dataset().row_count,Some(2));
    }
    #[test]
    fn sheets_and_derived_values_can_be_joined_without_carrying_formulas() {
        let dir=tempfile::tempdir().unwrap();let book=dir.path().join("book.xlsx");
        let mut workbook=rust_xlsxwriter::Workbook::new();
        let sheet=workbook.add_worksheet();sheet.set_name("Customers").unwrap();sheet.write_string(0,0,"id").unwrap();sheet.write_string(0,1,"name").unwrap();sheet.write_number(1,0,1.).unwrap();sheet.write_string(1,1,"Ana").unwrap();
        let sheet=workbook.add_worksheet();sheet.set_name("Orders").unwrap();sheet.write_string(0,0,"id").unwrap();sheet.write_string(0,1,"total").unwrap();sheet.write_number(1,0,1.).unwrap();sheet.write_number(1,1,12.).unwrap();workbook.save(&book).unwrap();
        assert_eq!(DataStore::list_sheets(&book).unwrap(),vec!["Customers","Orders"]);
        let customers=DataStore::open(&book,Some("Customers"),&dir.path().join("cache")).unwrap();
        let mut orders=DataStore::open(&book,Some("Orders"),&dir.path().join("cache")).unwrap();
        assert_ne!(customers.dataset().id,orders.dataset().id);
        let formula=crate::DerivedDefinition{id:"doubled".into(),name:"Doubled".into(),expression:"total * 2".into()};
        let preview=orders.preview_derived_column(&formula,None,&[]).unwrap();
        orders.create_derived_column(formula,&orders.dataset().revision,&preview.fingerprint).unwrap();
        let mut sources=vec![];
        for (alias,data) in [("customers",&customers),("orders",&orders)] {
            let path=dir.path().join(format!("{alias}.parquet"));
            data.export(ExportRequest{path:path.to_string_lossy().into(),format:ExportFormat::Parquet,filters:vec![],sorting:vec![],columns:data.dataset().columns.into_iter().map(|c|c.id).collect()}).unwrap();sources.push((alias.into(),path));
        }
        let scratch=tempfile::tempdir().unwrap();let out=dir.path().join("joined.parquet");
        materialize_query(&sources,"SELECT c.name, o.doubled FROM customers c JOIN orders o USING(id)",&out,scratch.path()).unwrap();
        let result=DataStore::open(&out,None,&dir.path().join("cache")).unwrap();
        let page=result.query_page(PageRequest{dataset_id:result.dataset().id,columns:vec!["name".into(),"doubled".into()],filters:vec![],sorting:vec![],offset:0,limit:10}).unwrap();
        assert_eq!(page.rows[0].values["doubled"],serde_json::json!(24.0));
    }
    #[test]
    fn query_cannot_read_files_mutate_config_or_execute_extra_statements() {
        let dir=tempfile::tempdir().unwrap();let sources=vec![snapshot(dir.path(),"a","id\n1\n")];
        for sql in ["SELECT 1); DROP TABLE a; SELECT (1", "ATTACH '/tmp/other'", "SELECT * FROM read_csv('/etc/passwd')", "SELECT * FROM query('SELECT * FROM read_csv(''/etc/passwd'')')", "SELECT 1); SET enable_external_access=true; --", "SELECT * FROM read_parquet('/tmp/no-file.parquet')", "SELECT * FROM glob('/etc/*')", "SELECT * FROM read_csv('https://example.com/data.csv')", "COPY a TO '/tmp/forbidden.csv'", "SET enable_external_access=true"] {
            let scratch=tempfile::tempdir().unwrap();let out=dir.path().join("bad.parquet");
            assert!(materialize_query(&sources,sql,&out,scratch.path()).is_err(),"accepted {sql}");assert!(!out.exists());
        }
    }
    #[test]
    fn even_existing_snapshot_paths_are_inaccessible_to_user_sql() {
        let dir=tempfile::tempdir().unwrap();let sources=vec![snapshot(dir.path(),"a","id\n1\n")];
        let scratch=tempfile::tempdir().unwrap();let out=dir.path().join("forbidden.parquet");
        let sql=format!("SELECT * FROM read_parquet({})",literal(&sources[0].1.to_string_lossy()));
        let failure=materialize_query(&sources,&sql,&out,scratch.path()).unwrap_err().to_string();
        assert!(failure.contains("disabled")||failure.contains("Permission"),"{failure}");assert!(!out.exists());
    }
    #[test]
    fn timed_out_query_is_joined_and_publishes_nothing() {
        let dir=tempfile::tempdir().unwrap();let sources=vec![snapshot(dir.path(),"a","id\n1\n")];
        let scratch=tempfile::tempdir().unwrap();let out=dir.path().join("timeout.parquet");
        let started=std::time::Instant::now();
        let result=materialize_with_timeout(&sources,"SELECT sum(a.i*b.i) FROM range(100000000) a(i) CROSS JOIN range(100000000) b(i)",&out,scratch.path(),Duration::from_millis(100));
        let failure=result.unwrap_err().to_string();
        assert!(failure.to_ascii_lowercase().contains("interrupt"),"{failure}");assert!(!out.exists());assert!(started.elapsed()<Duration::from_secs(10));
        // Scratch can be removed immediately: the query and interrupt thread have finished.
        scratch.close().unwrap();
    }
    #[test]
    fn failure_and_empty_results_preserve_inputs() {
        let dir=tempfile::tempdir().unwrap();let sources=vec![snapshot(dir.path(),"a","id\n1\n")];
        for sql in ["SELECT missing FROM a","SELECT * FROM range(1000001)"] {
            let scratch=tempfile::tempdir().unwrap();let out=dir.path().join("bad.parquet");assert!(materialize_query(&sources,sql,&out,scratch.path()).is_err());assert!(!out.exists());
        }
        let scratch=tempfile::tempdir().unwrap();let out=dir.path().join("empty.parquet");
        materialize_query(&sources,"SELECT * FROM a WHERE false;",&out,scratch.path()).unwrap();
        assert_eq!(DataStore::open(&out,None,&dir.path().join("cache")).unwrap().dataset().row_count,Some(0));
        assert!(sources[0].1.exists());
    }
}
