use datolens_enrichment::*;
use serde_json::{json,Value};
use std::{collections::{BTreeMap,BTreeSet},sync::{Arc,Mutex,atomic::{AtomicUsize,Ordering},mpsc},path::PathBuf,time::{SystemTime,UNIX_EPOCH}};
#[derive(Default)]
struct Data { values:Mutex<BTreeMap<String,BTreeMap<String,Value>>>, results:Mutex<BTreeMap<(String,String),Value>>, fail_apply:Mutex<bool> }
impl Data {fn new()->Self{Self{values:Mutex::new(BTreeMap::from([("r1".into(),BTreeMap::from([("x".into(),json!(1)),("secret".into(),json!("private"))])),("r2".into(),BTreeMap::from([("x".into(),json!(10))]))])),..Self::default()}}}
impl DataAccess for Data {
    fn dataset_revision(&self)->Result<String>{Ok("fixture-v1".into())}
    fn read_inputs(&self,row:&str,columns:&[String])->Result<InputSnapshot>{let rows=self.values.lock().unwrap();let r=rows.get(row).ok_or("Fila desconocida")?;Ok(InputSnapshot{revision:"fixture-v1".into(),values:columns.iter().filter_map(|c|r.get(c).map(|v|(c.clone(),v.clone()))).collect()})}
    fn apply_result(&self,row:&str,col:&str,value:&Value,_:&str)->Result<()>{if *self.fail_apply.lock().unwrap(){return Err("fail apply".into())}self.results.lock().unwrap().insert((row.into(),col.into()),value.clone());Ok(())}
}
struct NoKeys;
impl CredentialStore for NoKeys {fn key(&self,_:&str)->Result<String>{Err("No test credentials".into())}}
#[derive(Default)]struct Counting{calls:AtomicUsize, failing:BTreeSet<String>}
impl Provider for Counting{fn generate(&self,r:&ProviderRequest,c:&dyn CredentialStore)->Result<Value>{self.calls.fetch_add(1,Ordering::SeqCst);assert!(!r.inputs.contains_key("secret"));assert!(!r.prompt.contains("private"));MockProvider{failing_rows:self.failing.clone()}.generate(r,c)}}
fn dbpath()->PathBuf{std::env::temp_dir().join(format!("datolens-enrichment-test-{}-{}.sqlite",std::process::id(),SystemTime::now().duration_since(UNIX_EPOCH).unwrap().as_nanos()))}
fn open(path:&PathBuf,data:Arc<Data>,p:Arc<dyn Provider>)->Engine{Engine::open(path,data,Arc::new(NoKeys),p).unwrap()}
fn definition(id:&str,input:&str,dep:Option<&str>)->Definition{Definition{id:id.into(),name:id.into(),provider:"gemini".into(),model:"test-model".into(),prompt:format!("Use {{{{{input}}}}}"),input_columns:vec![input.into()],output_column:id.into(),output_kind:"numeric".into(),depends_on:dep.into_iter().map(str::to_string).collect(),revision:1}}
fn key(row:&str,def:&str)->CellKey{CellKey{row_id:row.into(),enrichment_id:def.into()}}
fn chain(e:&Engine){e.save_definition(definition("A","x",None)).unwrap();e.save_definition(definition("B","A",Some("A"))).unwrap();e.save_definition(definition("C","B",Some("B"))).unwrap()}
fn run(e:&Engine,cells:Vec<CellKey>,mode:RunMode,pre:bool)->RunStatus{let plan=e.plan(cells,mode,pre,false,3,100).unwrap();e.start(&plan.id).unwrap();drain(e,&plan.id)}
fn drain(e:&Engine,id:&str)->RunStatus{for _ in 0..20{let s=e.tick(id).unwrap();if s.state!=RunState::Running{return s;}}panic!("scheduler failed to terminate")}
#[test]fn chain_waits_and_pending_never_repeats_successes(){let d=Arc::new(Data::new());let p=Arc::new(Counting::default());let e=open(&dbpath(),d,p.clone());chain(&e);let s=run(&e,vec![key("r1","C")],RunMode::Pending,true);assert_eq!(s.state,RunState::Completed);assert_eq!(s.succeeded,3);assert_eq!(e.cell(&key("r1","C")).unwrap().value,Some(json!(4.0)));assert_eq!(p.calls.load(Ordering::SeqCst),3);run(&e,vec![key("r1","C")],RunMode::Pending,true);assert_eq!(p.calls.load(Ordering::SeqCst),3);}
#[test]fn cycle_and_undeclared_edges_rejected_atomically(){let e=open(&dbpath(),Arc::new(Data::new()),Arc::new(Counting::default()));chain(&e);let a=definition("A","C",Some("C"));assert!(e.save_definition(a).unwrap_err().contains("Ciclo"));assert_eq!(e.list_definitions().unwrap().iter().find(|d|d.id=="A").unwrap().revision,1);assert!(e.save_definition(definition("D","A",None)).is_err());}
#[test]fn partial_failure_keeps_other_row_chain(){let p=Arc::new(Counting{failing:BTreeSet::from(["r2".into()]),..Default::default()});let e=open(&dbpath(),Arc::new(Data::new()),p);chain(&e);let s=run(&e,vec![key("r1","C"),key("r2","C")],RunMode::Pending,true);assert_eq!(s.succeeded,3);assert_eq!(s.failed,3);assert_eq!(s.state,RunState::Failed);assert_eq!(e.cell(&key("r1","C")).unwrap().value,Some(json!(4.0)));}
#[test]fn input_and_prompt_invalidation_preserves_history(){let d=Arc::new(Data::new());let e=open(&dbpath(),d.clone(),Arc::new(Counting::default()));chain(&e);run(&e,vec![key("r1","C")],RunMode::Pending,true);d.values.lock().unwrap().get_mut("r1").unwrap().insert("x".into(),json!(20));e.invalidate_inputs("r1",&["x".into()]).unwrap();assert_eq!(e.cell(&key("r1","C")).unwrap().state,CellState::Stale);assert_eq!(e.cell(&key("r1","C")).unwrap().value,Some(json!(4.0)));run(&e,vec![key("r1","C")],RunMode::Pending,true);assert_eq!(e.cell(&key("r1","C")).unwrap().value,Some(json!(23.0)));assert_eq!(e.history(&key("r1","C")).unwrap().len(),2);let mut a=definition("A","x",None);a.prompt="New prompt {{x}}".into();e.save_definition(a).unwrap();assert_eq!(e.cell(&key("r1","B")).unwrap().state,CellState::Stale);assert_eq!(e.definition_history("A").unwrap().len(),2);}
#[test]fn missing_prerequisites_do_not_expand_scope_implicitly(){let e=open(&dbpath(),Arc::new(Data::new()),Arc::new(Counting::default()));chain(&e);let p=e.plan(vec![key("r1","C")],RunMode::Pending,false,false,2,10).unwrap();assert_eq!(p.cell_count,1);assert!(!p.missing_inputs.is_empty());e.start(&p.id).unwrap();let s=drain(&e,&p.id);assert_eq!(s.failed,1);assert_eq!(e.cell(&key("r1","A")).unwrap().attempts,0);let p=e.plan(vec![key("r2","A")],RunMode::Pending,false,true,2,10).unwrap();assert_eq!(p.cell_count,3);}
#[test]fn restart_recovers_running_without_repeating_success(){let path=dbpath();let d=Arc::new(Data::new());let provider=Arc::new(Counting::default());let e=open(&path,d.clone(),provider.clone());chain(&e);let p=e.plan(vec![key("r1","C")],RunMode::Pending,true,false,1,10).unwrap();e.start(&p.id).unwrap();e.tick(&p.id).unwrap();assert_eq!(e.cell(&key("r1","A")).unwrap().state,CellState::Succeeded);drop(e);
// Model a process killed after B was persisted as running, before its response arrived.
let db=rusqlite::Connection::open(&path).unwrap();let id=serde_json::to_string(&key("r1","B")).unwrap();let body:String=db.query_row("SELECT body FROM cells WHERE id=?1",[&id],|r|r.get(0)).unwrap();let mut cell:Cell=serde_json::from_str(&body).unwrap();cell.state=CellState::Running;db.execute("UPDATE cells SET body=?1 WHERE id=?2",rusqlite::params![serde_json::to_string(&cell).unwrap(),id]).unwrap();drop(db);
let e=open(&path,d,provider.clone());assert_eq!(e.status(&p.id).unwrap().state,RunState::Paused);assert_eq!(e.cell(&key("r1","B")).unwrap().state,CellState::Pending);assert_eq!(e.list_runs().unwrap().len(),1);e.resume(&p.id).unwrap();assert_eq!(drain(&e,&p.id).succeeded,3);assert_eq!(provider.calls.load(Ordering::SeqCst),3);}
struct BlockingProvider{entered:Mutex<mpsc::Sender<()>>,release:Mutex<mpsc::Receiver<()>>}
impl Provider for BlockingProvider{fn generate(&self,_:&ProviderRequest,_:&dyn CredentialStore)->Result<Value>{self.entered.lock().unwrap().send(()).unwrap();self.release.lock().unwrap().recv().unwrap();Ok(json!(999))}}
#[test]fn old_inflight_response_cannot_overwrite_new_prompt(){let (sent,recv)=mpsc::channel();let (release,wait)=mpsc::channel();let d=Arc::new(Data::new());let e=Arc::new(open(&dbpath(),d.clone(),Arc::new(BlockingProvider{entered:Mutex::new(sent),release:Mutex::new(wait)})));e.save_definition(definition("A","x",None)).unwrap();let p=e.plan(vec![key("r1","A")],RunMode::Pending,false,false,1,10).unwrap();e.start(&p.id).unwrap();let engine=e.clone();let id=p.id.clone();let worker=std::thread::spawn(move||engine.tick(&id).unwrap());recv.recv().unwrap();let mut def=definition("A","x",None);def.prompt="Changed {{x}}".into();e.save_definition(def).unwrap();release.send(()).unwrap();worker.join().unwrap();assert_eq!(e.cell(&key("r1","A")).unwrap().state,CellState::Stale);assert!(d.results.lock().unwrap().is_empty());assert_eq!(e.history(&key("r1","A")).unwrap()[0].state,CellState::Stale);assert_eq!(drain(&e,&p.id).state,RunState::Failed);}
#[test]fn cancelled_response_is_discarded(){let(sent,recv)=mpsc::channel();let(release,wait)=mpsc::channel();let d=Arc::new(Data::new());let e=Arc::new(open(&dbpath(),d.clone(),Arc::new(BlockingProvider{entered:Mutex::new(sent),release:Mutex::new(wait)})));e.save_definition(definition("A","x",None)).unwrap();let p=e.plan(vec![key("r1","A")],RunMode::Pending,false,false,1,10).unwrap();e.start(&p.id).unwrap();let engine=e.clone();let id=p.id.clone();let worker=std::thread::spawn(move||engine.tick(&id).unwrap());recv.recv().unwrap();e.cancel(&p.id).unwrap();release.send(()).unwrap();worker.join().unwrap();assert!(d.results.lock().unwrap().is_empty());assert_eq!(e.status(&p.id).unwrap().state,RunState::Cancelled);}
#[test]fn materialization_recovery_replays_without_provider(){let d=Arc::new(Data::new());*d.fail_apply.lock().unwrap()=true;let p=Arc::new(Counting::default());let e=open(&dbpath(),d.clone(),p.clone());e.save_definition(definition("A","x",None)).unwrap();let status=run(&e,vec![key("r1","A")],RunMode::Pending,false);assert_eq!(status.state,RunState::Paused);assert_eq!(e.cell(&key("r1","A")).unwrap().state,CellState::Succeeded);*d.fail_apply.lock().unwrap()=false;e.resume(&status.id).unwrap();assert_eq!(drain(&e,&status.id).state,RunState::Completed);assert_eq!(p.calls.load(Ordering::SeqCst),1);assert_eq!(d.results.lock().unwrap().get(&("r1".into(),"A".into())),Some(&json!(2.0)));}
struct Retry(AtomicUsize);
impl Provider for Retry{fn generate(&self,_:&ProviderRequest,_:&dyn CredentialStore)->Result<Value>{if self.0.fetch_add(1,Ordering::SeqCst)<2{Err("retryable: Gemini HTTP 429".into())}else{Ok(json!(1))}}}
#[test]fn retryable_failures_are_bounded_by_call_budget(){let p=Arc::new(Retry(AtomicUsize::new(0)));let e=open(&dbpath(),Arc::new(Data::new()),p.clone());e.save_definition(definition("A","x",None)).unwrap();let plan=e.plan(vec![key("r1","A")],RunMode::Pending,false,false,2,2).unwrap();e.start(&plan.id).unwrap();assert_eq!(drain(&e,&plan.id).state,RunState::Failed);assert_eq!(p.0.load(Ordering::SeqCst),2);}
#[test]fn output_validation_and_unselected_prompt_references(){assert!(validate_output("numeric",&json!("123")).is_err());assert!(validate_output("date",&json!("2025-02-29")).is_err());assert!(validate_output("date",&json!("2024-02-29")).is_ok());assert!(validate_output("multivalued",&json!(["a",2])).is_err());let e=open(&dbpath(),Arc::new(Data::new()),Arc::new(Counting::default()));let mut d=definition("A","x",None);d.prompt="Read {{secret}}".into();assert!(e.save_definition(d).is_err());}
#[test]fn changed_preview_and_call_limit_are_rejected(){let e=open(&dbpath(),Arc::new(Data::new()),Arc::new(Counting::default()));chain(&e);let p=e.plan(vec![key("r1","C")],RunMode::Pending,true,false,2,2).unwrap();assert!(e.start(&p.id).is_err());let p=e.plan(vec![key("r1","C")],RunMode::Pending,true,false,2,20).unwrap();let mut a=definition("A","x",None);a.prompt="new {{x}}".into();e.save_definition(a).unwrap();assert!(e.start(&p.id).is_err());}
