/** Local paginated data table with no feed or cloud dependencies. */
import { useMemo, useRef, useState } from 'react';
import type { Column, Page, ViewState } from '../../contracts/desktop-api';
import { cellKey, cellText, kindLabel, kindSymbol, moveItem, rectangularCells, type CellId, type ExplorerSelection } from './model';
interface Props { columns: Column[]; page: Page | null; view: ViewState; busy: boolean; selection: ExplorerSelection; onSelection: (selection: ExplorerSelection) => void; onView: (update: (view: ViewState) => ViewState) => void; offset: number; onCopy: () => void }
export function DataTable({ columns, page, view, busy, selection, onSelection, onView, offset, onCopy }: Props) {
  const anchor = useRef<CellId | null>(null);
  const dragging = useRef(false);
  const [dragColumn, setDragColumn] = useState<string | null>(null);
  const rows = page?.rows ?? [];
  const selectedCells = useMemo(() => new Set(selection.cells.map(cellKey)), [selection.cells]);
  const selectedRows = useMemo(() => new Set(selection.rowIds), [selection.rowIds]);
  const select = (cell: CellId, extend: boolean, toggle: boolean) => {
    if (extend && anchor.current) onSelection({ rowIds: [], cells: rectangularCells(rows, columns, anchor.current, cell) });
    else { anchor.current = cell; onSelection({ rowIds: [], cells: toggle ? selectedCells.has(cellKey(cell)) ? selection.cells.filter(c => cellKey(c) !== cellKey(cell)) : [...selection.cells, cell] : [cell] }); }
  };
  const sort = (id: string) => onView(v => { const rule = v.sorting.find(r => r.id === id); return { ...v, sorting: rule ? rule.desc ? v.sorting.filter(r => r.id !== id) : v.sorting.map(r => r.id === id ? { ...r, desc: true } : r) : [...v.sorting, { id, desc: false }] }; });
  return <div className="dl-table-scroll" tabIndex={0} aria-label="Tabla de datos. Mayúsculas selecciona un rango; Comando permite selección múltiple." aria-busy={busy} onPointerUp={() => { dragging.current = false; }} onPointerLeave={() => { dragging.current = false; }} onKeyDown={e => {
    if ((e.metaKey || e.ctrlKey) && e.key.toLowerCase() === 'c') { e.preventDefault(); if (!busy) onCopy(); }
    if (e.key === 'Escape') { onSelection({ cells: [], rowIds: [] }); anchor.current = null; }
    if ((e.metaKey || e.ctrlKey) && e.key.toLowerCase() === 'a') { e.preventDefault(); if (!busy) onSelection({ cells: [], rowIds: rows.map(row => row.id) }); }
  }}><table className="dl-table" style={{ width: columns.reduce((sum, col) => sum + (view.columns.widths[col.id] ?? 180), 48) }}><colgroup><col style={{ width: 48 }} />{columns.map(col => <col key={col.id} style={{ width: view.columns.widths[col.id] ?? 180 }} />)}</colgroup><thead><tr><th className="dl-row-index"><input type="checkbox" aria-label="Seleccionar todas las filas de esta página" disabled={busy || !rows.length} checked={rows.length > 0 && rows.every(r => selectedRows.has(r.id))} onChange={e => onSelection({ cells: [], rowIds: e.target.checked ? [...new Set([...selection.rowIds, ...rows.map(r => r.id)])] : selection.rowIds.filter(id => !rows.some(r => r.id === id)) })} /></th>{columns.map(col => { const priority = view.sorting.findIndex(r => r.id === col.id); return <th key={col.id} onDragOver={e => e.preventDefault()} onDrop={e => { e.preventDefault(); if (dragColumn) onView(v => ({ ...v, columns: { ...v.columns, order: moveItem(v.columns.order, v.columns.order.indexOf(dragColumn), v.columns.order.indexOf(col.id)) } })); setDragColumn(null); }}>
      <div className="dl-header-cell"><span className="dl-type" title={`${kindLabel[col.kind]} · ${col.dataType}`} draggable onDragStart={() => setDragColumn(col.id)}>{kindSymbol[col.kind]}</span><button onClick={() => sort(col.id)} title={`Ordenar ${col.name}; clics sucesivos: ascendente, descendente, sin orden`}>{col.name}</button>{priority >= 0 && <span className="dl-sort-indicator">{view.sorting[priority].desc ? '↓' : '↑'}{priority + 1}</span>}<button className="dl-hide-column" title={`Ocultar columna ${col.name}`} onClick={() => onView(v => ({ ...v, columns: { ...v.columns, hidden: [...v.columns.hidden, col.id] } }))}>×</button></div>
      <span className="dl-column-resize" role="separator" aria-label={`Ancho de ${col.name}`} aria-orientation="vertical" tabIndex={0} onKeyDown={e => { if (e.key === 'ArrowLeft' || e.key === 'ArrowRight') { e.preventDefault(); onView(v => ({ ...v, columns: { ...v.columns, widths: { ...v.columns.widths, [col.id]: Math.min(800, Math.max(90, (v.columns.widths[col.id] ?? 180) + (e.key === 'ArrowRight' ? 20 : -20))) } } })); } }} onPointerDown={e => { e.preventDefault(); e.currentTarget.setPointerCapture(e.pointerId); const start = e.clientX; const width = view.columns.widths[col.id] ?? 180; const target = e.currentTarget; const move = (ev: PointerEvent) => onView(v => ({ ...v, columns: { ...v.columns, widths: { ...v.columns.widths, [col.id]: Math.min(800, Math.max(90, width + ev.clientX - start)) } } })); const end = () => { target.removeEventListener('pointermove', move); target.removeEventListener('pointerup', end); target.removeEventListener('pointercancel', end); }; target.addEventListener('pointermove', move); target.addEventListener('pointerup', end); target.addEventListener('pointercancel', end); }} />
    </th>; })}</tr></thead><tbody>{!busy && rows.length === 0 ? <tr><td colSpan={columns.length + 1} className="dl-table-empty">No hay filas para estos filtros.</td></tr> : rows.map((row, index) => <tr key={row.id} className={selectedRows.has(row.id) ? 'is-row-selected' : ''}><td className="dl-row-index"><label><span>{offset + index + 1}</span><input type="checkbox" checked={selectedRows.has(row.id)} disabled={busy} aria-label={`Seleccionar fila ${offset + index + 1}`} onChange={e => onSelection({ cells: [], rowIds: e.target.checked ? [...selection.rowIds, row.id] : selection.rowIds.filter(id => id !== row.id) })} /></label></td>{columns.map(col => { const cell = { rowId: row.id, columnId: col.id }; const value = row.values[col.id]; return <td key={col.id} data-row-id={row.id} data-column-id={col.id} aria-selected={selectedCells.has(cellKey(cell))} className={`${selectedCells.has(cellKey(cell)) ? 'is-cell-selected' : ''} ${col.kind === 'numeric' ? 'is-number' : ''}`} title={value === null ? 'Valor nulo' : cellText(value)} onPointerDown={e => { if (busy || e.button !== 0) return; e.preventDefault(); e.currentTarget.closest<HTMLElement>('.dl-table-scroll')?.focus(); dragging.current = !e.metaKey && !e.ctrlKey; select(cell, e.shiftKey, e.metaKey || e.ctrlKey); }} onPointerEnter={e => { if (!busy && dragging.current && e.buttons === 1 && anchor.current) onSelection({ rowIds: [], cells: rectangularCells(rows, columns, anchor.current, cell) }); }} onKeyDown={e => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); if (!busy) select(cell, e.shiftKey, e.metaKey || e.ctrlKey); } }} tabIndex={0}>{value === null || value === undefined ? <span className="dl-null">null</span> : typeof value === 'boolean' ? <span className="dl-boolean">{value ? 'true' : 'false'}</span> : cellText(value)}</td>; })}</tr>)}</tbody></table>{busy && <div className="dl-table-loading" role="status">Consultando filas…</div>}</div>;
}
